# Generated by Django 3.2.6 on 2021-09-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shirt_size',
        ),
    ]
