# Generated by Django 3.2.6 on 2021-09-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('description_2', models.TextField(blank=True)),
                ('description_3', models.TextField(blank=True)),
                ('description_4', models.TextField(blank=True)),
                ('internal_memory', models.CharField(db_index=True, max_length=200)),
                ('internal_network', models.CharField(db_index=True, max_length=200)),
                ('photo_resolution', models.CharField(db_index=True, max_length=200)),
                ('number_simcard', models.CharField(db_index=True, max_length=200)),
                ('special_features', models.CharField(db_index=True, max_length=200)),
                ('dimensions', models.CharField(db_index=True, max_length=200)),
                ('description_simcard', models.CharField(db_index=True, max_length=200)),
                ('chipset', models.CharField(db_index=True, max_length=200)),
                ('type_Processor', models.CharField(db_index=True, max_length=200)),
                ('price', models.CharField(max_length=70)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Products_mobile',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
