# Generated by Django 3.2.6 on 2021-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_mobile',
            options={'ordering': ('name',), 'verbose_name_plural': 'Products_mobiles'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=70),
        ),
    ]
