# Generated by Django 3.2.6 on 2021-09-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=200, verbose_name='آدرس الکترونیکی')),
                ('massage', models.TextField(verbose_name='نام کاربر')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='مقاله')),
            ],
        ),
    ]
