# Generated by Django 3.2.6 on 2021-09-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='massage',
            field=models.TextField(verbose_name='متن نظر'),
        ),
    ]
