# Generated by Django 3.2.6 on 2021-11-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211108_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
